name: appmusicvol2
description: AppMusicVol2 - Modern SoundCloud-like local music player (UI first)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  path_provider: ^2.1.2
  path: ^1.9.0
  file_picker: ^6.1.1
  sqflite: ^2.3.2
  just_audio: ^0.9.36
  audio_service: ^0.18.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
